HomeDataCenterCore/Models/Test.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeDataCenterCore.Models
{
    public class Test
    {
    }
}

HomeDataCenterCore/Controllers/BodyDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HomeDataCenterCore.Services;
using HomeDataCenterCore.Domain;
using HomeDataCenterCore.Domain.ViewModels;

namespace HomeDataCenterCore.Controllers
{
    public class BodyDataController : Controller
    {
        private readonly Services.IBodyDataService _service;
        public BodyDataController(IBodyDataService service)
        {
            _service = service;
        }
        // GET: /<controller>/
        public async Task<IActionResult> Index(int page = 1)
        {
            ViewBag.Title = "身体数据 - 主页";
            int TotalCount = await _service.GetBodyDataCount();

            // 分页信息
            PagingInfo pagingInfo = new PagingInfo();
            pagingInfo.TotalCount = TotalCount;
            pagingInfo.CurrentPage = page;

            //Tuple<IEnumerable<BodyDataViewModel>, int> viewmodel = await _service.GetAllBodyData();
            //viewModel.BodyData = await _service.GetAllBodyDataByPage(page, pagingInfo.PageSize);
            //return View(viewmodel.Item1.OrderBy(m => m.RecordTime));
            var data = await _service.GetAllBodyDataByPage(page, pagingInfo.PageSize);
            ViewBag.PagingInfo = pagingInfo;
            return View(data);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Title = "身体数据 - 新增";
            BodyDataViewModel viewmodel = new BodyDataViewModel()
            {
                RecordTime = DateTime.Now
            };
            return View(viewmodel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(BodyDataViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _service.AddBodyData(model);
            }
            else
            {
                ViewBag.Title = "身体数据 - 新增";
                ViewBag.Msg = "数据合法性检测失败";
                return View(model);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

HomeDataCenterCore/Controllers/FilmDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HomeDataCenterCore.Services;
using HomeDataCenterCore.Domain.DomainModels;
using HomeDataCenterCore.Domain.ViewModels;

namespace HomeDataCenterCore.Controllers
{
    public class FilmDataController : Controller
    {
        private readonly IFilmDataService _service;
        public FilmDataController(IFilmDataService service)
        {
            _service = service;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int page = 1)
        {
            ViewBag.Title = "电影数据 - 主页";
            int TotalCount = await _service.GetFilmDataCount();

            // 分页
            PagingInfo pagingInfo = new PagingInfo();
            pagingInfo.TotalCount = TotalCount;
            pagingInfo.CurrentPage = page;

            // 获取数据
            var data = await _service.GetFilmDataByPage(page, pagingInfo.PageSize);
            ViewBag.PagingInfo = pagingInfo;
            return View(data);
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int Id)
        {
            FilmData data = await _service.GetFilmDetailById(Id);
            ViewBag.Title = $"{data.Name} - 详情";
            return View(data);
        }
    }
}

HomeDataCenterCore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HomeDataCenterCore.Services;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace HomeDataCenterCore.Controllers
{
    public class HomeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewBag.Title = "主页";
            return View();
        }
    }
}

HomeDataCenterCore/ViewComponents/PageLinkViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HomeDataCenterCore.Domain;
using HomeDataCenterCore.Domain.ViewModels;

namespace HomeDataCenterCore.ViewComponents
{
    public class PageLinkViewComponent : ViewComponent
    {
        public PageLinkViewComponent()
        {
            
        }

        public async Task<IViewComponentResult> InvokeAsync(string controller, string action, PagingInfo pagingInfo)
        {
            // TODO:分页的样式需要修改
            PagingViewModel model = await Task.Factory.StartNew(() =>
            {
                PagingViewModel viewmodel = new PagingViewModel();

                viewmodel.controller = controller;
                viewmodel.action = action;
                viewmodel.FirstIndex = pagingInfo.CurrentPage == 1 ? 0 : 1;
                viewmodel.PreIndex = pagingInfo.CurrentPage <= 1 ? 0 : pagingInfo.CurrentPage - 1;
                viewmodel.NextIndex = pagingInfo.CurrentPage >= pagingInfo.PageCount ? 0 : pagingInfo.CurrentPage + 1;
                viewmodel.LastIndex = pagingInfo.CurrentPage >= pagingInfo.PageCount ? 0 : pagingInfo.PageCount;
                viewmodel.Summary = $"共{pagingInfo.TotalCount}条记录,第{pagingInfo.CurrentPage}/{pagingInfo.PageCount}页";

                int IndexCount = 7;
                int StartIndex = pagingInfo.CurrentPage;
                int EndIndex = pagingInfo.CurrentPage;

                // 确定当前页前面的页数
                if ((StartIndex - IndexCount / 2) <= 0)
                {
                    StartIndex = 1;
                }
                else
                {
                    StartIndex = StartIndex - IndexCount / 2;
                }

                // 确定当前页后面的页数(此时前面的页数小于等于一半)
                int tempIndexCount = IndexCount - (pagingInfo.CurrentPage - StartIndex + 1);
                if (EndIndex + tempIndexCount >= pagingInfo.PageCount)
                {
                    EndIndex = pagingInfo.PageCount;
                }
                else
                {
                    EndIndex = EndIndex + tempIndexCount;
                }

                // 检查页数是否已满，不够的从前面取
                int NeedCount = IndexCount - (EndIndex - StartIndex + 1);
                if (NeedCount > 0)
                {
                    if (StartIndex - NeedCount <= 0)
                    {
                        StartIndex = 1;
                    }
                    else
                    {
                        StartIndex = StartIndex - NeedCount;
                    }
                }

                // 插入字典
                for (int i = StartIndex; i <= EndIndex; i++)
                {
                    if (i == pagingInfo.CurrentPage)
                    {
                        viewmodel.PageLinks.Add(i, string.Empty);
                    }
                    else
                    {
                        viewmodel.PageLinks.Add(i, i.ToString());
                    }
                }

                return viewmodel;
            });
            return View(model);
        }
    }
}

HomeDataCenterCore/Views/BodyData/Create.cshtml
@model BodyDataViewModel

<div class="row">
    <div class="col-12">
        <h1>@ViewBag.Title</h1>
        <a class="btn-sm btn-info" asp-action="Index">
            身体数据首页
        </a>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-12">
        <form asp-action="Create">
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        @Html.DisplayNameFor(model => model.RecordTime)
                    </span>
                </div>
                <input asp-for="RecordTime" class="form-control" type="datetime-local" />
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        @Html.DisplayNameFor(model => model.Shape)
                    </span>
                </div>
                <input asp-for="Shape" class="form-control" type="text" />
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        @Html.DisplayNameFor(model => model.Weight)
                    </span>
                </div>
                <input asp-for="Weight" class="form-control" type="number" />
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        @Html.DisplayNameFor(model => model.BMI)
                    </span>
                </div>
                <input asp-for="BMI" class="form-control" type="number" />
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        @Html.DisplayNameFor(model => model.BodyFatPercentage)
                    </span>
                </div>
                <input asp-for="BodyFatPercentage" class="form-control" type="number" />
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        @Html.DisplayNameFor(model => model.BodyMoisture)
                    </span>
                </div>
                <input asp-for="BodyMoisture" class="form-control" type="number" />
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        @Html.DisplayNameFor(model => model.SkeletalMuscleRate)
                    </span>
                </div>
                <input asp-for="SkeletalMuscleRate" class="form-control" type="number" />
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        @Html.DisplayNameFor(model => model.MuscleMass)
                    </span>
                </div>
                <input asp-for="MuscleMass" class="form-control" type="number" />
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        @Html.DisplayNameFor(model => model.BoneMass)
                    </span>
                </div>
                <input asp-for="BoneMass" class="form-control" type="number" />
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        @Html.DisplayNameFor(model => model.FatFreeBodyWeight)
                    </span>
                </div>
                <input asp-for="FatFreeBodyWeight" class="form-control" type="number" />
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        @Html.DisplayNameFor(model => model.Protein)
                    </span>
                </div>
                <input asp-for="Protein" class="form-control" type="number" />
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        @Html.DisplayNameFor(model => model.SubcutaneousFat)
                    </span>
                </div>
                <input asp-for="SubcutaneousFat" class="form-control" type="number" />
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        @Html.DisplayNameFor(model => model.VisceralFatGrade)
                    </span>
                </div>
                <input asp-for="VisceralFatGrade" class="form-control" type="number" />
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        @Html.DisplayNameFor(model => model.BodyAge)
                    </span>
                </div>
                <input asp-for="BodyAge" class="form-control" type="number" />
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        @Html.DisplayNameFor(model => model.BasalMetabolism)
                    </span>
                </div>
                <input asp-for="BasalMetabolism" class="form-control" type="number" />
            </div>
            <button class="btn btn-primary" type="submit">保存</button>
        </form>
    </div>
</div>

HomeDataCenterCore/Views/BodyData/DisplayTemplates/BodyDataViewModel.cshtml
@using HomeDataCenterCore.Domain.ViewModels
@model BodyDataViewModel

<tr>
    <th>
        @Model.RecordTime.ToString("yyyy-MM-dd HH:mm:ss")
    </th>
    <th>
        @Model.Shape
    </th>
    <th>
        @Model.Weight
    </th>
    <th>
        @Model.BMI
    </th>
    <th>
        @Model.BodyFatPercentage
    </th>
    <th>
        @Model.BodyMoisture
    </th>
    <th>
        @Model.SkeletalMuscleRate
    </th>
    <th>
        @Model.MuscleMass
    </th>
    <th>
        @Model.BoneMass
    </th>
    <th>
        @Model.FatFreeBodyWeight
    </th>
    <th>
        @Model.Protein
    </th>
    <th>
        @Model.SubcutaneousFat
    </th>
    <th>
        @Model.VisceralFatGrade
    </th>
    <th>
        @Model.BodyAge
    </th>
    <th>
        @Model.BasalMetabolism
    </th>
</tr>

HomeDataCenterCore/Views/BodyData/Index.cshtml
@model IEnumerable<BodyDataViewModel>


<div class="row">
    <div class="col-12">
        <h1>@ViewBag.Title</h1>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <a class="btn btn-info" asp-action="Create">新增数据</a>
    </div>
</div>
<div class="row">
    <div class="col-12 table-responsive">
        <table class="table table-bordered">
            <thead class="thead-light">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.RecordTime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Shape)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Weight)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.BMI)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.BodyFatPercentage)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.BodyMoisture)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SkeletalMuscleRate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.MuscleMass)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.BoneMass)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FatFreeBodyWeight)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Protein)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SubcutaneousFat)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.VisceralFatGrade)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.BodyAge)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.BasalMetabolism)
                    </th>
                </tr>
            </thead>
            <tbody>
                @Html.DisplayForModel()
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <vc:page-link controller="BodyData" action="Index" paging-info="ViewBag.PagingInfo">
        </vc:page-link>
    </div>
</div>

HomeDataCenterCore/Views/FilmData/Detail.cshtml
@model HomeDataCenterCore.Domain.DomainModels.FilmData

<h1>@ViewBag.Title</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilmId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FilmId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Language)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Language)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilmType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FilmType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OtherCNFilmName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OtherCNFilmName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OtherENFilmName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OtherENFilmName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlayTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlayTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlayType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlayType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlayInfo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlayInfo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShootingTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShootingTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilmingLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FilmingLocation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserRating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserRating)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-info" asp-action="Index">返回</a>
</div>

HomeDataCenterCore/Views/FilmData/DisplayTemplates/FilmDataViewModel.cshtml
@model HomeDataCenterCore.Domain.ViewModels.FilmDataViewModel

<tr>
    <th style="display:none;">
        @Model.Id
    </th>
    <th>
        @Html.ActionLink(Model.Name, "Detail", "FilmData", new { Id = Model.Id })
    </th>
    <th>
        @Model.Country
    </th>
    <th>
        @Model.Language
    </th>
    <th>
        @Model.FilmType
    </th>
    <th>
        @Model.PlayType
    </th>
    <th>
        @Model.UserRating
    </th>
</tr>

HomeDataCenterCore/Views/FilmData/Index.cshtml
@model IEnumerable<HomeDataCenterCore.Domain.ViewModels.FilmDataViewModel>

<div class="row">
    <div class="col-12">
        <h1>@ViewBag.Title</h1>
    </div>
</div>

<div class="row">
    <div class="col-12 table-responsive">
        <table class="table table-bordered">
            <thead class="thead-light">
                <tr>
                    <th style="display:none">
                        @Html.DisplayNameFor(model => model.Id)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Country)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Language)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FilmType)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PlayType)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.UserRating)
                    </th>
                </tr>
            </thead>
            <tbody>
                @Html.DisplayForModel()
            </tbody>
        </table>
    </div>

</div>

<div class="row">
    <div class="col-12">
        <vc:page-link controller="FilmData" action="Index" paging-info="ViewBag.PagingInfo">
        </vc:page-link>
    </div>
</div>

HomeDataCenterCore/Views/Home/Index.cshtml
<div class="row">
    <div class="col-12">
        <div class="card mt-4 bg-light">
            <div class="card-body">
                <a asp-controller="BodyData" asp-action="Index">
                    <h4 class="card-title">
                        身体数据
                    </h4>
                </a>
            </div>
        </div>
        <div class="card mt-4 bg-light">
            <div class="card-body">
                <a asp-controller="FilmData" asp-action="Index">
                    <h4 class="card-title">
                        电影数据
                    </h4>
                </a>
            </div>
        </div>
    </div>
</div>

HomeDataCenterCore/Views/Shared/Components/PageLink/Default.cshtml
@using HomeDataCenterCore.Domain.ViewModels
@model PagingViewModel

<ul class="pagination">
    @if (Model.FirstIndex == 0)
    {
        <li class="page-item disabled">
            <a class="page-link ">首页</a>
        </li>
    }
    else
    {
        <li class="page-item">
            <a class="page-link" asp-controller="@Model.controller" asp-action="@Model.action" asp-route-page="@Model.FirstIndex">首页</a>
        </li>
    }
    @if (Model.PreIndex == 0)
    {
        <li class="page-item disabled">
            <a class="page-link">上页</a>
        </li>
    }
    else
    {
        <li class="page-item">
            <a class="page-link" asp-controller="@Model.controller" asp-action="@Model.action" asp-route-page="@Model.PreIndex">上页</a>
        </li>
    }

    @foreach (var pl in Model.PageLinks)
    {

        @if (string.IsNullOrEmpty(pl.Value))
        {
            <li class="page-item active">
                <a class="page-link">@pl.Key</a>
            </li>
        }
        else
        {
            <li class="page-item">
                <a class="page-link" asp-controller="@Model.controller" asp-action="@Model.action" asp-route-page="@pl.Key">@pl.Key</a>
            </li>
        }

    }
    @if (Model.NextIndex == 0)
    {
        <li class="page-item disabled">
            <a class="page-link">下页</a>
        </li>
    }
    else
    {
        <li class="page-item">
            <a class="page-link" asp-controller="@Model.controller" asp-action="@Model.action" asp-route-page="@Model.NextIndex">下页</a>
        </li>
    }

    @if (Model.LastIndex == 0)
    {
        <li class="page-item disabled">
            <a class="page-link">末页</a>
        </li>
    }
    else
    {
        <li class="page-item">
            <a class="page-link" asp-controller="@Model.controller" asp-action="@Model.action" asp-route-page="@Model.LastIndex">末页</a>

        </li>
    }

    <li class="page-item disabled">
        <a class="page-link ">@Model.Summary</a>
    </li>
</ul>

HomeDataCenterCore/Views/Shared/Components/Paging/Default.cshtml
@using HomeDataCenterCore.Domain.ViewModels
@model PagingViewModel

<div>
    <ul class="Paging" style="clear: both;">
        <li>
            @if (string.IsNullOrEmpty(Model.FirstUrl))
            {
                <a>首页</a>
            }
            else
            {
                <a href="@Model.FirstUrl">首页</a>
            }
        </li>
        <li>
            @if (string.IsNullOrEmpty(Model.PreLink))
            {
                <a>上页</a>
            }
            else
            {
                <a href="@Model.PreLink">上页</a>
            }
        </li>
        @foreach (var pl in Model.PageLinks)
        {

            <li>
                @if (string.IsNullOrEmpty(pl.Value))
                {
                    <a>@pl.Key</a>
                }
                else
                {
                    <a href="@pl.Value">@pl.Key</a>
                }
            </li>
        }
        <li>
            @if (string.IsNullOrEmpty(Model.NextLink))
            {
                <a>下页</a>
            }
            else
            {
                <a href="@Model.NextLink">下页</a>
            }
        </li>
        <li>
            @if (string.IsNullOrEmpty(Model.LastLink))
            {
                <a>末页</a>
            }
            else
            {
                <a href="@Model.LastLink">末页</a>
            }
        </li>
        <li>
            <span>
                @Model.Summary
            </span>
        </li>
    </ul>
</div>

HomeDataCenterCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/Site.css"/>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="~/css/Site.css"/>
    <style>
        th td{
            text-align: left;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <a asp-controller="Home" asp-action="Index" class="navbar-brand">
            家庭数据中心
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="BodyData" asp-action="Index">身体数据</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="FilmData" asp-action="Index">电影数据</a>
                </li>
            </ul>
        </div>
    </nav>
    
    <div class="container-fluid">
        @RenderBody()
    </div>
    <hr />
    <div style="height:200px">
        copyright@2019
    </div>
</body>
</html>